### ISSUE TITLE
New name for CLI

### ISSUE THREAD

**Issue by ByteDream** [ByteDream/crunchy-cli#39]
Beginning with version **v3**, this repo splits up in 2 seperate packages. One containing only the go library and the second the cli part.
This allows me to add more dependencies to the cli without bloating up the library and structure the code more the way I like it. There are probably some people who only use the library and don't need the cli part.

The library should keep the name _crunchyroll-go_ to not break dependencies and because it's the most descriptive for a library, so the cli part needs a new name.

Post your naming suggestions as a reply in this issue if you have any good idea.
React to a suggestion 👍 or 👎 if you like or dislike it.

**Comment by IchBinLeoon** [comment]
I would keep it very simple: `crunchyroll-cli`

**Comment by ByteDream** [comment]
I received another suggestion: `crunchydl`

**Comment by lncndev** [comment]
A few ideas:
 - `crunchy`
 - `crunchy-cli`
 - `roll-cli`
 - `cliroll`
 - `crdl`

**Comment by ByteDream** [comment]
I've chosen `crunchy-cli` as new name. Thank y'all for your name suggestions^^
